export enum YES_NO {
	YES = "Yes",
	NO = "No",
}

export enum VEHICLE_ACCIDENT_PHOTO_CATEGORY {
	BCEW_VEHICLE = "BCEW_VEHICLE",
	OTHER_VEHICLE_PROPERTY = "OTHER_VEHICLE_PROPERTY",
	INSURANCE_CORRESPONDENCE = "INSURANCE_CORRESPONDENCE",
	SUPPORTING_DOCUMENT = "SUPPORTING_DOCUMENT",
	REPAIR_ESTIMATE = "REPAIR_ESTIMATE",
}

export enum JOB_SITE_TYPE {
	BCEW_SITE = "BCEW_SITE",
	CONTRACTOR_SITE = "CONTRACTOR_SITE",
}

export enum WEATHER_CONDITION {
	SUNNY = "SUNNY",
	RAINY = "RAINY",
	SNOW_ICE = "SNOW_ICE",
}

// Per other-vehicle photo groups.
export enum OTHER_VEHICLE_IMAGE_CATEGORY {
	INSURANCE_CARD = "INSURANCE_CARD",
	DRIVERS_LICENSE = "DRIVERS_LICENSE",
	VEHICLE_DAMAGE = "VEHICLE_DAMAGE",
}

export enum JOB_SITE_INJURY_MEDICAL_ACTION {
	NO_ACTION = "NO_ACTION",
	TREATMENT_NEEDED = "TREATMENT_NEEDED",
	TREATMENT_AND_DRUG_SCREEN = "TREATMENT_AND_DRUG_SCREEN",
	// Admin-only: their form asks about the drug screen and medical care
	// separately, so a drug screen with no treatment is expressible there. The
	// technician's single-choice question can't produce it.
	DRUG_SCREEN_ONLY = "DRUG_SCREEN_ONLY",
}

export enum MEDICAL_DRUG_SCREEN {
	NO_ACTION = "NO_ACTION",
	DRUG_SCREEN_ONLY = "DRUG_SCREEN_ONLY",
	DRUG_SCREEN_MEDICAL = "DRUG_SCREEN_MEDICAL",
}

// Sentinel select value for a treatment location not in the managed list.
export const MEDICAL_TREATMENT_LOCATION_OTHER = "OTHER";

export enum SAFETY_REPORT_STATUS {
	DRAFT = "DRAFT",
	PENDING = "PENDING",
	PENDING_SECOND_REVIEW = "PENDING_SECOND_REVIEW",
	RESOLVED_INTERNALLY = "RESOLVED_INTERNALLY",
	SUBMITTED_TO_INSURANCE = "SUBMITTED_TO_INSURANCE",
	RESOLVED = "RESOLVED",
}

// A missing source means the report was submitted from the technician-side form.
export enum REPORT_SOURCE {
	EMPLOYEE = "EMPLOYEE",
	OFFICE = "OFFICE",
}

export enum TECHNICIAN_REPORT_STATUS {
	DRAFT = "DRAFT",
	PENDING = "PENDING",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
	ADDITIONAL_INFO_REQUESTED = "ADDITIONAL_INFO_REQUESTED",
}

export enum MY_RECORD_TAB {
	ALL = "ALL",
	DRAFT = "DRAFT",
	PENDING = "PENDING",
	ADDITIONAL_INFO_REQUESTED = "ADDITIONAL_INFO_REQUESTED",
}

export enum SAFETY_REPORT_TYPE {
	VEHICLE_ACCIDENT = "VEHICLE_ACCIDENT",
	JOB_SITE_INJURY = "JOB_SITE_INJURY",
}

export enum PERSON_STRUCK_TYPE {
	EMPLOYEE = "EMPLOYEE",
	OTHER = "OTHER",
}

// Accident-form sections an admin can ask the technician to complete.
export enum ACCIDENT_SECTION {
	ACCIDENT_DETAILS = "ACCIDENT_DETAILS",
	FOLLOW_UP = "FOLLOW_UP",
	WHAT_HAPPENED = "WHAT_HAPPENED",
	REQUIRED_PHOTOS = "REQUIRED_PHOTOS",
	POLICE = "POLICE",
	OTHER_VEHICLE = "OTHER_VEHICLE",
	PERSON_INVOLVED = "PERSON_INVOLVED",
	TOW_IMPOUND = "TOW_IMPOUND",
}

// These two are prompt-only for the admin, so they're always part of an
// "ask technician" request and cannot be removed.
export const MANDATORY_ASK_TECHNICIAN_SECTIONS: ACCIDENT_SECTION[] = [
	ACCIDENT_SECTION.WHAT_HAPPENED,
	ACCIDENT_SECTION.REQUIRED_PHOTOS,
];
