export enum YES_NO {
	YES = "Yes",
	NO = "No",
}

export enum VEHICLE_ACCIDENT_PHOTO_CATEGORY {
	BCEW_VEHICLE = "VEHICLE",
	OTHER_VEHICLE_PROPERTY = "OTHER_VEHICLE_PROPERTY",
	INSURANCE_CORRESPONDENCE = "INSURANCE_CORRESPONDENCE",
	SUPPORTING_DOCUMENT = "SUPPORTING_DOCUMENT",
	REPAIR_ESTIMATE = "REPAIR_ESTIMATE",
}

export enum WEATHER_CONDITION {
	SUNNY = "SUNNY",
	RAINY = "RAINY",
	SNOW_ICE = "SNOW_ICE",
}

export enum JOB_SITE_INJURY_MEDICAL_ACTION {
	NO_ACTION = "NO_ACTION",
	TREATMENT_NEEDED = "TREATMENT_NEEDED",
	TREATMENT_AND_DRUG_SCREEN = "TREATMENT_AND_DRUG_SCREEN",
}

export enum MEDICAL_DRUG_SCREEN {
	NO_ACTION = "NO_ACTION",
	DRUG_SCREEN_ONLY = "DRUG_SCREEN_ONLY",
	DRUG_SCREEN_MEDICAL = "DRUG_SCREEN_MEDICAL",
}

// Sentinel select value for a treatment location not in the managed list.
export const MEDICAL_TREATMENT_LOCATION_OTHER = "OTHER";

export enum SAFETY_REPORT_STATUS {
	DRAFT = "DRAFT",
	SUBMITTED = "SUBMITTED",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
}

export enum TECHNICIAN_REPORT_STATUS {
	DRAFT = "DRAFT",
	PENDING = "PENDING",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
}

export enum MY_RECORD_TAB {
	ALL = "ALL",
	DRAFT = "DRAFT",
	PENDING = "PENDING",
}

export enum SAFETY_REPORT_TYPE {
	VEHICLE_ACCIDENT = "VEHICLE_ACCIDENT",
	JOB_SITE_INJURY = "JOB_SITE_INJURY",
}
