export enum RequestTypeEnum {
	VEHICLE_BREAKDOWN = "VEHICLE_BREAKDOWN",
	VEHICLE_MAINTENANCE = "VEHICLE_MAINTENANCE",
	ADD_NEW_STOP = "ADD_NEW_STOP",
}

export enum StopType {
	PROJECT = "PROJECT",
	SPECIAL = "SPECIAL",
}
