export enum INCIDENT_REPORT_STATUS {
	DRAFT = "DRAFT",
	PENDING = "PENDING",
	PENDING_SECOND_REVIEW = "PENDING_SECOND_REVIEW",
	COORDINATE = "COORDINATE",
	WITH_INSURANCE = "WITH_INSURANCE",
	RESOLVED = "RESOLVED",
	REJECTED = "REJECTED",
}

export enum INCIDENT_SEVERITY {
	LOW = "LOW",
	MEDIUM = "MEDIUM",
	HIGH = "HIGH",
	CRITICAL = "CRITICAL",
}

export enum INCIDENT_SOURCE {
	ADMIN = "ADMIN",
	GEOTAB = "GEOTAB",
	DRIVER = "DRIVER",
}

export enum INCIDENT_TYPE {
	VEHICLE_ACCIDENT = "VEHICLE_ACCIDENT",
	VEHICLE_BREAKDOWN = "VEHICLE_BREAKDOWN",
}

export enum INCIDENT_TYPE_TAB {
	ALL = "ALL",
	ACCIDENTS = "ACCIDENTS",
	BREAKDOWN = "BREAKDOWN",
}
