export enum INCIDENT_REPORT_STATUS {
	DRAFT = "DRAFT",
	PENDING = "PENDING",
	PENDING_SECOND_REVIEW = "PENDING_SECOND_REVIEW",
	PENDING_THIRD_REVIEW = "PENDING_THIRD_REVIEW",
	COORDINATE = "COORDINATE",
	WITH_INSURANCE = "WITH_INSURANCE",
	RESOLVED = "RESOLVED",
	REJECTED = "REJECTED",
	ADDITIONAL_INFO_REQUESTED = "ADDITIONAL_INFO_REQUESTED",
}

export enum INCIDENT_SEVERITY {
	LOW = "LOW",
	MEDIUM = "MEDIUM",
	HIGH = "HIGH",
	CRITICAL = "CRITICAL",
}

export enum INCIDENT_SOURCE {
	ADMIN = "ADMIN",
	GEOTAB = "GEOTAB",
	DRIVER = "DRIVER",
}

// Which "Violation type" dropdown(s) a DrivingSafetyViolationType shows up on.
export enum VIOLATION_TYPE_CATEGORY {
	ACCIDENT_VIOLATION = "ACCIDENT_VIOLATION",
	DRIVING_SAFETY_VIOLATION = "DRIVING_SAFETY_VIOLATION",
}

export enum INCIDENT_TYPE {
	VEHICLE_ACCIDENT = "VEHICLE_ACCIDENT",
	VEHICLE_BREAKDOWN = "VEHICLE_BREAKDOWN",
	DRIVING_SAFETY_VIOLATION = "DRIVING_SAFETY_VIOLATION",
}

export enum INCIDENT_TYPE_TAB {
	ALL = "ALL",
	ACCIDENTS = "ACCIDENTS",
	VIOLATIONS = "VIOLATIONS",
	BREAKDOWN = "BREAKDOWN",
	DRAFTS = "DRAFTS",
}

export enum ACCIDENT_STATUS_ACTION {
	MARK_FOR_PRESIDENT_REVIEW = "MARK_FOR_PRESIDENT_REVIEW",
	APPROVE_AND_SEND_TO_INSURANCE = "APPROVE_AND_SEND_TO_INSURANCE",
	RESOLVE_INTERNALLY = "RESOLVE_INTERNALLY",
	MARK_RESOLVED = "MARK_RESOLVED",
}

export enum SECOND_REVIEW_ACTION {
	APPROVE = "APPROVE",
	APPROVE_INTERNALLY = "APPROVE_INTERNALLY",
	CANCEL = "CANCEL",
}

export enum THIRD_REVIEW_ACTION {
	SEND_BACK = "SEND_BACK",
	SEND_TO_INSURANCE = "SEND_TO_INSURANCE",
}

export enum INCIDENT_AUDIT_ACTION {
	SUBMITTED = "SUBMITTED",
	APPROVED_INTERNALLY = "APPROVED_INTERNALLY",
	VIOLATION_UPDATED = "VIOLATION_UPDATED",
	ADMIN_UPDATED_FIELD = "ADMIN_UPDATED_FIELD",
	ADMIN_INPUTS_EDITED = "ADMIN_INPUTS_EDITED",
	TECHNICIAN_INFO_EDITED = "TECHNICIAN_INFO_EDITED",
	ADMIN_REQUESTED_INFO = "ADMIN_REQUESTED_INFO",
	ASSIGNED_SECOND_REVIEW = "ASSIGNED_SECOND_REVIEW",
	SECOND_REVIEW_APPROVED = "SECOND_REVIEW_APPROVED",
	SECOND_REVIEW_CANCELLED = "SECOND_REVIEW_CANCELLED",
	THIRD_REVIEW_SENT_BACK = "THIRD_REVIEW_SENT_BACK",
	SENT_TO_INSURANCE = "SENT_TO_INSURANCE",
	CLAIM_RESOLVED = "CLAIM_RESOLVED",
}

// Role an actor held when they took an audited action — drives the "{Role} did X"
// audit-trail titles. Resolved on the backend from the actor's Role.name.
export enum INCIDENT_ACTOR_ROLE {
	TECHNICIAN = "TECHNICIAN",
	ADMIN = "ADMIN",
	PRESIDENT = "PRESIDENT",
	FLEET_MANAGER = "FLEET_MANAGER",
}

// Field keys carried on ADMIN_UPDATED_FIELD audit entries (fieldName), mapped to
// display labels in the audit trail.
export enum ACCIDENT_ADMIN_FIELD {
	DRUG_SCREEN = "DRUG_SCREEN",
	MEDICAL_LOCATION = "MEDICAL_LOCATION",
	BCEW_TOWED = "BCEW_TOWED",
	OTHER_VEHICLE_TOWED = "OTHER_VEHICLE_TOWED",
	VEHICLE_IMPOUNDED = "VEHICLE_IMPOUNDED",
}

// Technician-info field keys carried on TECHNICIAN_INFO_EDITED audit entries.
export enum ACCIDENT_TECHNICIAN_FIELD {
	ON_JOB_SITE = "ON_JOB_SITE",
	JOB_SITE_TYPE = "JOB_SITE_TYPE",
	ANOTHER_VEHICLE_INVOLVED = "ANOTHER_VEHICLE_INVOLVED",
	PERSON_STRUCK = "PERSON_STRUCK",
	OTHER_VEHICLE_COUNT = "OTHER_VEHICLE_COUNT",
	TRUCK_NUMBER = "TRUCK_NUMBER",
	VIN = "VIN",
	LICENSE_PLATE = "LICENSE_PLATE",
	ACCIDENT_DATE = "ACCIDENT_DATE",
	ACCIDENT_TIME = "ACCIDENT_TIME",
	LOCATION = "LOCATION",
	NEAREST_CROSS_STREET = "NEAREST_CROSS_STREET",
	WEATHER = "WEATHER",
	DESCRIBE_ACCIDENT = "DESCRIBE_ACCIDENT",
	DAMAGE_TO_BCEW_VEHICLE = "DAMAGE_TO_BCEW_VEHICLE",
	POLICE_CONTACTED = "POLICE_CONTACTED",
	POLICE_DEPARTMENT = "POLICE_DEPARTMENT",
	POLICE_REPORT_NUMBER = "POLICE_REPORT_NUMBER",
}
