import { ATTENDANCE_APPROVAL_STATUS, ATTENDANCE_REASON, EMPLOYMENT_STATUS, WORKSITE_TYPE } from "../enums";
import { IAttendanceDashboardData } from "../types";

export const buildMockAttendanceDashboard = (): IAttendanceDashboardData => ({
	stats: {
		pendingReview: { value: 7, subtitle: "Awaiting your action" },
		approved: { value: 24, subtitle: "77.4% approval rate" },
		rejected: { value: 7 },
		totalRequests: { value: 31, subtitle: "24 approved · 7 rejected" },
		lateArrival: { value: 9 },
		earlyQuit: { value: 7 },
		fullDayOff: { value: 15 },
	},
	topTypes: [
		{ label: "Sickness (Employee)", count: 18 },
		{ label: "Personal", count: 12 },
		{ label: "Late Arrival (>15 min)", count: 8 },
		{ label: "Transportation", count: 6 },
		{ label: "Sickness (Family)", count: 5 },
		{ label: "Vacation", count: 3 },
	],
	pointAssessmentSummary: [
		{ label: "Total points issued", points: 47 },
		{ label: "Points pending", points: 12 },
		{ label: "Overrides", points: 3 },
		{ label: "Late arrival (no notice)", points: 2 },
		{ label: "Personal (no notice)", points: 1 },
		{ label: "Excused absence", points: 1 },
	],
	pointEscalationPolicy: [
		{ label: "Employee notified", points: 3 },
		{ label: "Verbal / coaching session", points: 5 },
		{ label: "Written warning to file", points: 10 },
		{ label: "Review — possible termination", points: 15 },
		{ label: "Termination", points: 25 },
	],
	pendingApprovals: [
		{
			id: "1",
			requestId: "ATT-2026-042",
			user: { name: "Shannon O'Keefe" },
			employmentStatus: EMPLOYMENT_STATUS.CURRENT,
			worksiteType: WORKSITE_TYPE.FIELD,
			reason: ATTENDANCE_REASON.FULL_DAY_OFF,
			note: "Sick (Employee)",
			scheduledTime: null,
			actualTime: null,
			submissionDate: "2026-06-25T00:00:00.000Z",
			requestedTimeOffRange: "06/26 - 06/30",
			ptoStatus: ATTENDANCE_APPROVAL_STATUS.PENDING,
		},
		{
			id: "2",
			requestId: "ATT-2026-043",
			user: { name: "Brian Blanda" },
			employmentStatus: EMPLOYMENT_STATUS.FORMER,
			worksiteType: WORKSITE_TYPE.OFFICE,
			reason: ATTENDANCE_REASON.LATE_ARRIVAL,
			note: "Family Sickness",
			scheduledTime: "2026-06-25T08:30:00.000Z",
			actualTime: "2026-06-25T10:30:00.000Z",
			submissionDate: "2026-06-25T00:00:00.000Z",
			requestedTimeOffRange: "06/26 - 06/30",
			ptoStatus: ATTENDANCE_APPROVAL_STATUS.PENDING,
		},
		{
			id: "3",
			requestId: "ATT-2026-044",
			user: { name: "Norma Huels" },
			employmentStatus: EMPLOYMENT_STATUS.CURRENT,
			worksiteType: WORKSITE_TYPE.WAREHOUSE,
			reason: ATTENDANCE_REASON.LATE_ARRIVAL,
			note: "Accident (Out of Work)",
			scheduledTime: "2026-06-25T08:30:00.000Z",
			actualTime: "2026-06-25T10:30:00.000Z",
			submissionDate: "2026-06-25T00:00:00.000Z",
			requestedTimeOffRange: "06/26 - 06/30",
			ptoStatus: ATTENDANCE_APPROVAL_STATUS.PENDING,
		},
		{
			id: "4",
			requestId: "ATT-2026-045",
			user: { name: "Norma Huels" },
			employmentStatus: EMPLOYMENT_STATUS.CURRENT,
			worksiteType: WORKSITE_TYPE.WAREHOUSE,
			reason: ATTENDANCE_REASON.EARLY_QUIT,
			note: "Accident (Out of Work)",
			scheduledTime: "2026-06-25T14:30:00.000Z",
			actualTime: "2026-06-25T13:15:00.000Z",
			submissionDate: "2026-06-25T00:00:00.000Z",
			requestedTimeOffRange: "06/26 - 06/30",
			ptoStatus: ATTENDANCE_APPROVAL_STATUS.PENDING,
		},
		{
			id: "5",
			requestId: "ATT-2026-046",
			user: { name: "Norma Huels" },
			employmentStatus: EMPLOYMENT_STATUS.CURRENT,
			worksiteType: WORKSITE_TYPE.WAREHOUSE,
			reason: ATTENDANCE_REASON.LEAVE_RETURN_SAME_DAY,
			note: "Accident (Out of Work)",
			scheduledTime: "2026-06-25T08:30:00.000Z",
			actualTime: "2026-06-25T13:00:00.000Z",
			submissionDate: "2026-06-25T00:00:00.000Z",
			requestedTimeOffRange: "06/26 - 06/30",
			ptoStatus: ATTENDANCE_APPROVAL_STATUS.PENDING,
		},
		{
			id: "6",
			requestId: "ATT-2026-047",
			user: { name: "Norma Huels" },
			employmentStatus: EMPLOYMENT_STATUS.CURRENT,
			worksiteType: WORKSITE_TYPE.WAREHOUSE,
			reason: ATTENDANCE_REASON.LATE_ARRIVAL,
			note: "Medical Appointment",
			scheduledTime: "2026-06-25T11:00:00.000Z",
			actualTime: "2026-06-25T10:30:00.000Z",
			submissionDate: "2026-06-25T00:00:00.000Z",
			requestedTimeOffRange: "06/26 - 06/30",
			ptoStatus: ATTENDANCE_APPROVAL_STATUS.PENDING,
		},
	],
});
