export enum ADD_RECORD_TAB {
	VEHICLE_ACCIDENT = "VEHICLE_ACCIDENT",
	DRIVING_SAFETY_VIOLATION = "DRIVING_SAFETY_VIOLATION",
	VEHICLE_BREAKDOWN = "VEHICLE_BREAKDOWN",
}

export const ADD_RECORD_TAB_PARAM = "tab";
