export enum NOTIFICATION_TARGET {
	EMPLOYEE = "EMPLOYEE",
	ADMIN = "ADMIN",
}

export enum NOTIFICATION_TITLE {
	EMPLOYEE_ALERT = "Employee Alert",
	JOB_MARK_AS_NOT_READY = "Job Mark As Not Ready",
	JOB_UPDATE_REMINDER = "Job Update Reminder",
	OVERTIME_REQUEST = "Overtime Request",
	DAY_LOG_TIME_MISMATCH = "Day Log Time mismatch",
	EARLY_DAY_START = "Early Day Start",
	FOREMAN_ADDED_STOP = "Foreman Added Stop",
	ADMIN_JOB_ALERT = "Admin Job Alert",
	ADMIN_ALERT = "Admin Alert",
	JOB_NOT_COMPLETED = "Job Not Completed",
	ETR = "ETR",
	JOB_TIME_OVERRIDE = "Job Time Override",
	EMPLOYEE_RESCHEDULED_JOB = "Employee Rescheduled Job",
	JOB_SCHEDULE_DATE_CHANGED = "Job Schedule Date Changed",
	EMPLOYEE_LATE_REASON = "Employee Late Reason",
	LATENESS_ALERT = "Lateness Alert",
	EMPLOYEE_ADDED_NOTE = "Employee Added Note",
	ATTENDANCE_APPROVAL = "Attendance ",
	TECHNICAL_ISSUE = "Technical Issue",
	MIDDAY_STOP = "New Job Request",
	GPS_TIME_MISMATCH = "GPS Time Mismatch",
	TECHNICAL_ISSUE_UPDATE = "Technical Issue Update",
	TRAVEL_PAY_REQUEST = "Travel Pay Request",
	LATE_DAY_START = "LATE_DAY_START",
	EMPLOYEE_GPS_OFFLINE = "GPS Alert!",
	RELEASE_NOTE = "Release Note",
	APP_UPDATES = "App Updates",
	GEOTAB_REGAINED_POWER = "Geotab Regain Power",
	CREW_ASSIGNED_TO_JOB = "Crew Assigned to Job",
	SUBCONTRACTOR_JOB_CREATED_AND_CREW_ASSIGNMENT = "Crew Assigned by Subcontractor Admin",
	JOB_MARKED_AS_DNW = "Job Marked As Did Not Work",
	LATE_START_AND_EARLY_QUIT = "Late Start & Early Quit",
	MATERIAL_REQUEST = "Material Request",
	MISSING_ITEM_REQUEST = "Unknown Item Request",
	MATERIAL_REQUEST_ASSIGNED = "Material Request Assigned",
	MATERIAL_REQUEST_APPROVED = "Material Request Approved",
	MATERIAL_REQUEST_REJECTED = "Material Request Rejected",
	MISSING_ITEM_REQUEST_NOTE = "Unknown Item Request Note",
	MATERIAL_REQUEST_NOTE = "Material Request Note",
	ROLES_AND_PERMISSIONS_UPDATED = "Roles and Permissions Updated",
}

//  each gruop can have multiple notifications for that we are using key
export enum NOTIFICATION_KEY {
	EMPLOYEE_ALERT = "EMPLOYEE_ALERT",
	JOB_MARK_AS_NOT_READY = "JOB_MARK_AS_NOT_READY",
	JOB_MARK_AS_READY = "JOB_MARK_AS_READY",
	JOB_UPDATE_REMINDER = "JOB_UPDATE_REMINDER",
	LOG_TIME_REMINDER = "LOG_TIME_REMINDER",
	OVERTIME_REQUEST = "OVERTIME_REQUEST",
	EMPLOYEE_REMOVED_FROM_DAILY_JOB = "EMPLOYEE_REMOVED_FROM_DAILY_JOB",
	DAY_LOG_TIME_MISMATCH = "DAY_LOG_TIME_MISMATCH",
	EARLY_DAY_START = "EARLY_DAY_START",
	FOREMAN_ADDED_STOP = "FOREMAN_ADDED_STOP",
	ADMIN_JOB_ALERT = "ADMIN_JOB_ALERT",
	ADMIN_ALERT = "ADMIN_ALERT",
	ADMIN_JOB_DELETED = "ADMIN_JOB_DELETED",
	VEHICLE_SWAP = "VEHICLE_SWAP",
	JOB_NOT_COMPLETED = "JOB_NOT_COMPLETED",
	JOB_COMPLETED = "JOB_COMPLETED",
	LATE_DAY_START = "LATE_DAY_START",
	ETR = "ETR",
	GPS_TIME_MISMATCH = "GPS_TIME_MISMATCH",
	SCHEDULE_PUBLISHED = "SCHEDULE_PUBLISHED",
	JOB_DATE_UPDATE = "JOB_DATE_UPDATE",
	JOB_TIME_OVERRIDE = "JOB_TIME_OVERRIDE",
	EMPLOYEE_RESCHEDULED_JOB = "EMPLOYEE_RESCHEDULED_JOB",
	JOB_SCHEDULE_DATE_CHANGED = "JOB_SCHEDULE_DATE_CHANGED",
	LATENESS_ALERT = "LATENESS_ALERT",
	EMPLOYEE_LATE_REASON = "EMPLOYEE_LATE_REASON",
	EMPLOYEE_ADDED_NOTE = "EMPLOYEE_ADDED_NOTE",
	JOB_MARK_AS_NOT_READY_BY_EMPLOYEE = "JOB_MARK_AS_NOT_READY_BY_EMPLOYEE",
	ATTENDANCE_APPROVAL = "ATTENDANCE_APPROVAL",
	MIDDAY_STOP = "NEW_JOB_REQUEST",
	TECHNICAL_ISSUE = "TECHNICAL_ISSUE",
	TECHNICAL_ISSUE_UPDATE = "TECHNICAL_ISSUE_UPDATE",
	TRAVEL_PAY_REQUEST = "TRAVEL_PAY_REQUEST",
	TRAVEL_PAY_REQUEST_NOTE_ADDED = "TRAVEL_PAY_REQUEST_NOTE_ADDED",
	TRAVEL_PAY_REQUEST_CREATED = "TRAVEL_PAY_REQUEST_CREATED",
	SYSTEM_TRAVEL_PAY_REQUEST_STATUS_UPDATE = "SYSTEM_TRAVEL_PAY_REQUEST_STATUS_UPDATE",
	ADMIN_ALLOW_WEEKEND_SELF_SCHEDULING = "ADMIN_ALLOW_WEEKEND_SELF_SCHEDULING",
	ADMIN_DISALLOW_WEEKEND_SELF_SCHEDULING = "ADMIN_DISALLOW_WEEKEND_SELF_SCHEDULING",
	EMPLOYEE_WEEKEND_SELF_SCHEDULED_JOB = "EMPLOYEE_WEEKEND_SELF_SCHEDULED_JOB",
	EMPLOYEE_SELF_SCHEDULED_JOB = "EMPLOYEE_SELF_SCHEDULED_JOB",
	EMPLOYEE_GPS_OFFLINE = "GPS_ALERT",
	RELEASE_NOTE = "RELEASE_NOTE",
	APP_UPDATES = "APP_UPDATES",
	JOB_PUBLISH = "JOB_PUBLISH",
	GEOTAB_REGAINED_POWER = "GEOTAB_REGAINED_POWER",
	ADMIN_UPDATE_WEEKEND_WORKING_MODE = "ADMIN_UPDATE_WEEKEND_WORKING_MODE",
	WEEKEND_VOLUNTARY_REQUEST_SENT = "WEEKEND_VOLUNTARY_REQUEST_SENT",
	WEEKEND_VOLUNTARY_RESPONSE_SUBMITTED = "WEEKEND_VOLUNTARY_RESPONSE_SUBMITTED",
	WEEKEND_VOLUNTARY_EMPLOYEE_RESPONSE_REVIEWED = "WEEKEND_VOLUNTARY_EMPLOYEE_RESPONSE_REVIEWED",
	WEEKEND_SLOT_AVAILABLE = "WEEKEND_SLOT_AVAILABLE",
	CREW_ASSIGNED_TO_JOB = "CREW_ASSIGNED_TO_JOB",
	SUBCONTRACTOR_JOB_CREATED_AND_CREW_ASSIGNMENT = "SUBCONTRACTOR_JOB_CREATED_AND_CREW_ASSIGNMENT",
	WORK_ORDER_SCHEDULED = "WORK_ORDER_SCHEDULED",
	USER_WEEKEND_WORK_DELETED = "USER_WEEKEND_WORK_DELETED",
	JOB_MARKED_AS_DNW = "JOB_MARKED_AS_DNW",
	ADMIN_ALLOW_SELF_SCHEDULING = "ADMIN_ALLOW_SELF_SCHEDULING",
	ADMIN_DISALLOW_SELF_SCHEDULING = "ADMIN_DISALLOW_SELF_SCHEDULING",
	JOB_MARK_AS_NOT_READY_BY_SUB_CREW = "JOB_MARK_AS_NOT_READY_BY_SUB_CREW",
	JOB_NOT_COMPLETED_BY_SUB_CREW = "JOB_NOT_COMPLETED_BY_SUB_CREW",
	LATE_START_AND_EARLY_QUIT = "LATE_START_AND_EARLY_QUIT",
	GPS_AFTER_HOUR_USAGE = "GPS_AFTER_HOUR_USAGE",
	GPS_IDLE_TIME = "GPS_IDLE_TIME",
	GPS_AFTER_HOUR_USAGE_NOTE = "GPS_AFTER_HOUR_USAGE_NOTE",
	MATERIAL_REQUEST = "MATERIAL_REQUEST",
	MISSING_ITEM_REQUEST = "MISSING_ITEM_REQUEST",
	MATERIAL_REQUEST_ASSIGNED = "MATERIAL_REQUEST_ASSIGNED",
	MATERIAL_REQUEST_APPROVED = "MATERIAL_REQUEST_APPROVED",
	MATERIAL_REQUEST_REJECTED = "MATERIAL_REQUEST_REJECTED",
	MISSING_ITEM_REQUEST_NOTE = "MISSING_ITEM_REQUEST_NOTE",
	MATERIAL_REQUEST_NOTE = "MATERIAL_REQUEST_NOTE",
	MATERIAL_REQUEST_APPROVED_CREW = "MATERIAL_REQUEST_APPROVED_CREW",
	MATERIAL_REQUEST_REJECTED_CREW = "MATERIAL_REQUEST_REJECTED_CREW",
	MATERIAL_REQUEST_REASSIGNED = "MATERIAL_REQUEST_REASSIGNED",
	MATERIAL_REQUEST_REASSIGNED_CREW = "MATERIAL_REQUEST_REASSIGNED_CREW",
	MATERIAL_REQUEST_CROSS_ASSIGNED = "MATERIAL_REQUEST_CROSS_ASSIGNED",
	FINGERPRINT_WORKING_INDICATED = "FINGERPRINT_WORKING_INDICATED",
	FINGERPRINT_LEAVE_CONFIRMED = "FINGERPRINT_LEAVE_CONFIRMED",
	ROLE_PERMISSION_UPDATED = "ROLE_PERMISSION_UPDATED",
	USER_PERMISSION_UPDATED = "USER_PERMISSION_UPDATED",
	USER_ROLE_UPDATED = "USER_ROLE_UPDATED",
	MISSING_ITEM_REQUEST_REJECTED = "MISSING_ITEM_REQUEST_REJECTED",
	MISSING_ITEM_CONVERTED_TO_MATERIAL_REQUEST = "MISSING_ITEM_CONVERTED_TO_MATERIAL_REQUEST",
	VEHICLE_ACCIDENT_REPORTED = "VEHICLE_ACCIDENT_REPORTED",
	VEHICLE_ACCIDENT_PERSON_STRUCK = "VEHICLE_ACCIDENT_PERSON_STRUCK",
	VEHICLE_ACCIDENT_INFO_REQUESTED = "VEHICLE_ACCIDENT_INFO_REQUESTED",
	VEHICLE_ACCIDENT_INFO_RECEIVED = "VEHICLE_ACCIDENT_INFO_RECEIVED",
	VEHICLE_ACCIDENT_MARKED_FOR_PRESIDENT_REVIEW = "VEHICLE_ACCIDENT_MARKED_FOR_PRESIDENT_REVIEW",
	VEHICLE_ACCIDENT_PENDING_PRESIDENT_REVIEW = "VEHICLE_ACCIDENT_PENDING_PRESIDENT_REVIEW",
	VEHICLE_ACCIDENT_INTERNALLY_RESOLVED = "VEHICLE_ACCIDENT_INTERNALLY_RESOLVED",
	VEHICLE_ACCIDENT_READY_FOR_INSURANCE = "VEHICLE_ACCIDENT_READY_FOR_INSURANCE",
	VEHICLE_ACCIDENT_INSURANCE_SUBMITTED = "VEHICLE_ACCIDENT_INSURANCE_SUBMITTED",
	DRUG_SCREEN_REQUIRED_COORDINATOR = "DRUG_SCREEN_REQUIRED_COORDINATOR",
	DRUG_SCREEN_REQUIRED_TECHNICIAN = "DRUG_SCREEN_REQUIRED_TECHNICIAN",
	DRUG_SCREEN_REQUIRED_ADMIN = "DRUG_SCREEN_REQUIRED_ADMIN",
	VEHICLE_BREAKDOWN_REPORTED = "VEHICLE_BREAKDOWN_REPORTED",
	DRIVING_SAFETY_VIOLATION_REPORTED = "DRIVING_SAFETY_VIOLATION_REPORTED",
	JOB_SITE_INJURY_REPORTED = "JOB_SITE_INJURY_REPORTED",
	JOB_SITE_SAFETY_REPORT_CREATED_BY_ADMIN = "JOB_SITE_SAFETY_REPORT_CREATED_BY_ADMIN",
	JOB_SITE_SAFETY_VIOLATION_REPORTED = "JOB_SITE_SAFETY_VIOLATION_REPORTED",
	JOB_SITE_SAFETY_MARKED_FOR_PRESIDENT_REVIEW = "JOB_SITE_SAFETY_MARKED_FOR_PRESIDENT_REVIEW",
	JOB_SITE_SAFETY_PENDING_PRESIDENT_REVIEW = "JOB_SITE_SAFETY_PENDING_PRESIDENT_REVIEW",
	JOB_SITE_SAFETY_INTERNALLY_RESOLVED = "JOB_SITE_SAFETY_INTERNALLY_RESOLVED",
	JOB_SITE_SAFETY_RESOLVED = "JOB_SITE_SAFETY_RESOLVED",
	JOB_SITE_SAFETY_CLOSED_FOR_TECHNICIAN = "JOB_SITE_SAFETY_CLOSED_FOR_TECHNICIAN",
}

// type is group of notifications
export enum NOTIFICATION_TYPE {
	VEHICLE_SWAP = "VEHICLE_SWAP",
	JOB_NOT_COMPLETED = "JOB_NOT_COMPLETED",
	JOB_MARK_AS_NOT_READY = "JOB_MARK_AS_NOT_READY",
	DAY_LOG_TIME_MISMATCH = "DAY_LOG_TIME_MISMATCH",
	EARLY_DAY_START = "EARLY_DAY_START",
	LATE_DAY_START = "LATE_DAY_START",
	FOREMAN_ADDED_STOP = "FOREMAN_ADDED_STOP",
	LOG_TIME_REMINDER = "LOG_TIME_REMINDER",
	ETR = "ETR",
	GPS_TIME_MISMATCH = "GPS_TIME_MISMATCH",
	SCHEDULE_PUBLISHED = "SCHEDULE_PUBLISHED",
	JOB_DATE_UPDATE = "JOB_DATE_UPDATE",
	JOB_TIME_OVERRIDE = "JOB_TIME_OVERRIDE",
	JOB_UPDATE_REMINDER = "JOB_UPDATE_REMINDER",
	EMPLOYEE_REMOVED_FROM_DAILY_JOB = "EMPLOYEE_REMOVED_FROM_DAILY_JOB",
	EMPLOYEE_RESCHEDULED_JOB = "EMPLOYEE_RESCHEDULED_JOB",
	JOB_SCHEDULE_DATE_CHANGED = "JOB_SCHEDULE_DATE_CHANGED",
	EMPLOYEE_LATE_REASON = "EMPLOYEE_LATE_REASON",
	LATENESS_ALERT = "LATENESS_ALERT",
	EMPLOYEE_ADDED_NOTE = "EMPLOYEE_ADDED_NOTE",
	ATTENDANCE_APPROVAL = "ATTENDANCE_APPROVAL",
	TECHNICAL_ISSUE = "TECHNICAL_ISSUE",
	MIDDAY_STOP = "NEW_JOB_REQUEST",
	TECHNICAL_ISSUE_UPDATE = "TECHNICAL_ISSUE_UPDATE",
	TRAVEL_PAY_REQUEST = "TRAVEL_PAY_REQUEST",
	WEEKEND_SELF_SCHEDULING = "WEEKEND_SELF_SCHEDULING",
	EMPLOYEE_GPS_OFFLINE = "GPS_ALERT",
	RELEASE_NOTE = "RELEASE_NOTE",
	APP_UPDATES = "APP_UPDATES",
	GEOTAB_REGAINED_POWER = "GEOTAB_REGAINED_POWER",
	WEEKEND_SCHEDULE = "WEEKEND_SCHEDULE",
	CREW_ASSIGNED_TO_JOB = "CREW_ASSIGNED_TO_JOB",
	SUBCONTRACTOR_JOB_CREATED_AND_CREW_ASSIGNMENT = "SUBCONTRACTOR_JOB_CREATED_AND_CREW_ASSIGNMENT",
	WORK_ORDER = "WORK_ORDER",
	JOB_MARKED_AS_DNW = "JOB_MARKED_AS_DNW",
	SELF_SCHEDULING = "SELF_SCHEDULING",
	LATE_START_AND_EARLY_QUIT = "LATE_START_AND_EARLY_QUIT",
	GPS_EXCEPTION_EVENT = "GPS_EXCEPTION_EVENT",
	MATERIAL_REQUEST = "MATERIAL_REQUEST",
	ROLES_AND_PERMISSIONS_UPDATED = "ROLES_AND_PERMISSIONS_UPDATED",
	VEHICLE_ACCIDENT_REPORT = "VEHICLE_ACCIDENT_REPORT",
	VEHICLE_BREAKDOWN_REPORT = "VEHICLE_BREAKDOWN_REPORT",
	DRIVING_SAFETY_VIOLATION_REPORT = "DRIVING_SAFETY_VIOLATION_REPORT",
	JOB_SITE_INJURY_REPORT = "JOB_SITE_INJURY_REPORT",
	JOB_SITE_SAFETY_VIOLATION_REPORT = "JOB_SITE_SAFETY_VIOLATION_REPORT",
}

export type INotification = {
	id: string;
	message: string;
	title: NOTIFICATION_TITLE;
	senderId: string;
	createdAt: string;
	updatedAt: string;
	target: NOTIFICATION_TARGET;
	type: NOTIFICATION_TYPE;
	key: NOTIFICATION_KEY;
	data: string;
};

export type ISubContractorCrewNotification = {
	id: string;
	subcontractorCrewId: string;
	notificationId: string;
	isRead: boolean;
};

export type IUserNotification = {
	id: string;
	userId: string;
	notificationId: string;
	isRead: boolean;
	createdAt: string;
	updatedAt: string;
};

export type INotificationDataMap = {
	[NOTIFICATION_KEY.EMPLOYEE_ALERT]: null;
	[NOTIFICATION_KEY.JOB_MARK_AS_NOT_READY]: { dailyJobId: string };
	[NOTIFICATION_KEY.JOB_UPDATE_REMINDER]: { dailyJobId: string };
	[NOTIFICATION_KEY.OVERTIME_REQUEST]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.DAY_LOG_TIME_MISMATCH]: { employeeId: string; date: string };
	[NOTIFICATION_KEY.EARLY_DAY_START]: { employeeId: string; date: string };
	[NOTIFICATION_KEY.LATE_DAY_START]: { employeeId: string; date: string };
	[NOTIFICATION_KEY.FOREMAN_ADDED_STOP]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.ADMIN_JOB_ALERT]: { dailyJobId: string };
	[NOTIFICATION_KEY.ADMIN_ALERT]: null;
	[NOTIFICATION_KEY.JOB_NOT_COMPLETED]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.JOB_COMPLETED]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.ETR]: { id: string };
	[NOTIFICATION_KEY.JOB_TIME_OVERRIDE]: { dailyJobId: string };
	[NOTIFICATION_KEY.EMPLOYEE_RESCHEDULED_JOB]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.JOB_SCHEDULE_DATE_CHANGED]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.EMPLOYEE_LATE_REASON]: { employeeId: string; date: string };
	[NOTIFICATION_KEY.LATE_START_AND_EARLY_QUIT]: { employeeId: string; date: string };
	[NOTIFICATION_KEY.LATENESS_ALERT]: null;
	[NOTIFICATION_KEY.EMPLOYEE_ADDED_NOTE]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.ATTENDANCE_APPROVAL]: null;
	[NOTIFICATION_KEY.TECHNICAL_ISSUE]: {
		technicalIssueId: string;
		ticketNumber: string;
		reporterId: string;
	};
	[NOTIFICATION_KEY.MIDDAY_STOP]: { id: string; dailyJobId: string };
	[NOTIFICATION_KEY.GPS_TIME_MISMATCH]: { employeeId: string; date: string };
	[NOTIFICATION_KEY.TECHNICAL_ISSUE_UPDATE]: {
		issueId: string;
	};
	[NOTIFICATION_KEY.TRAVEL_PAY_REQUEST]: {
		travelPayRequestId: string;
		date: string;
	};
	[NOTIFICATION_KEY.SCHEDULE_PUBLISHED]: { startDate: string; endDate: string };
	[NOTIFICATION_KEY.JOB_DATE_UPDATE]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.JOB_TIME_OVERRIDE]: { dailyJobId: string };
	[NOTIFICATION_KEY.EMPLOYEE_REMOVED_FROM_DAILY_JOB]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.TRAVEL_PAY_REQUEST_NOTE_ADDED]: { travelPayRequestId: string; date: string };
	[NOTIFICATION_KEY.TRAVEL_PAY_REQUEST_CREATED]: { travelPayRequestId: string; date: string };
	[NOTIFICATION_KEY.SYSTEM_TRAVEL_PAY_REQUEST_STATUS_UPDATE]: null;
	[NOTIFICATION_KEY.ADMIN_JOB_DELETED]: null;
	[NOTIFICATION_KEY.VEHICLE_SWAP]: { employeeId: string; date: string };
	[NOTIFICATION_KEY.JOB_MARK_AS_NOT_READY_BY_EMPLOYEE]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.LOG_TIME_REMINDER]: null;
	[NOTIFICATION_KEY.JOB_MARK_AS_READY]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.ADMIN_ALLOW_WEEKEND_SELF_SCHEDULING]: null;
	[NOTIFICATION_KEY.ADMIN_DISALLOW_WEEKEND_SELF_SCHEDULING]: null;
	[NOTIFICATION_KEY.EMPLOYEE_WEEKEND_SELF_SCHEDULED_JOB]: { date: string; dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.EMPLOYEE_SELF_SCHEDULED_JOB]: { date: string; dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.EMPLOYEE_GPS_OFFLINE]: null;
	[NOTIFICATION_KEY.RELEASE_NOTE]: { date: string };
	[NOTIFICATION_KEY.APP_UPDATES]: { date: string };
	[NOTIFICATION_KEY.JOB_PUBLISH]: { dailyJobId: string; jobName: string };
	[NOTIFICATION_KEY.GEOTAB_REGAINED_POWER]: null;
	[NOTIFICATION_KEY.ADMIN_UPDATE_WEEKEND_WORKING_MODE]: { date: string };
	[NOTIFICATION_KEY.WEEKEND_VOLUNTARY_REQUEST_SENT]: { date: string };
	[NOTIFICATION_KEY.WEEKEND_VOLUNTARY_RESPONSE_SUBMITTED]: null;
	[NOTIFICATION_KEY.WEEKEND_VOLUNTARY_EMPLOYEE_RESPONSE_REVIEWED]: { date: string };
	[NOTIFICATION_KEY.WEEKEND_SLOT_AVAILABLE]: { date: string };
	[NOTIFICATION_KEY.CREW_ASSIGNED_TO_JOB]: null;
	[NOTIFICATION_KEY.SUBCONTRACTOR_JOB_CREATED_AND_CREW_ASSIGNMENT]: null;
	[NOTIFICATION_KEY.USER_WEEKEND_WORK_DELETED]: null;
	[NOTIFICATION_KEY.WORK_ORDER_SCHEDULED]: { date: string; bcewSrvinvId: string; ordnum: string };
	[NOTIFICATION_KEY.JOB_MARKED_AS_DNW]: { dailyJobId: string; jobName: string; date: string; userId: string };
	[NOTIFICATION_KEY.ADMIN_ALLOW_SELF_SCHEDULING]: null;
	[NOTIFICATION_KEY.ADMIN_DISALLOW_SELF_SCHEDULING]: null;
	[NOTIFICATION_KEY.JOB_MARK_AS_NOT_READY_BY_SUB_CREW]: {
		dailyJobId: string;
	};
	[NOTIFICATION_KEY.JOB_NOT_COMPLETED_BY_SUB_CREW]: {
		dailyJobId: string;
	};
	[NOTIFICATION_KEY.GPS_IDLE_TIME]: {
		eventId: string;
		date: string;
	};
	[NOTIFICATION_KEY.GPS_AFTER_HOUR_USAGE]: {
		eventId: string;
		date: string;
		userId: string;
	};
	[NOTIFICATION_KEY.GPS_AFTER_HOUR_USAGE_NOTE]: {
		userId: string;
		date: string;
		userName?: string;
		explanation?: string;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST]: {
		materialRequestId: number;
	};
	[NOTIFICATION_KEY.MISSING_ITEM_REQUEST]: {
		missingItemRequestId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_ASSIGNED]: {
		pullListItemId: string;
		requestId: number;
		assignTo: string;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_APPROVED]: {
		pullListItemId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_REJECTED]: {
		pullListItemId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MISSING_ITEM_REQUEST_NOTE]: {
		missingItemRequestId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_NOTE]: {
		pullListItemId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_APPROVED_CREW]: {
		pullListItemId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_REJECTED_CREW]: {
		pullListItemId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_REASSIGNED]: {
		pullListItemId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_REASSIGNED_CREW]: {
		pullListItemId: string;
		requestId: number;
	};
	[NOTIFICATION_KEY.MATERIAL_REQUEST_CROSS_ASSIGNED]: {
		pullListItemId: string;
		requestId: number;
		assignTo: string;
	};
	[NOTIFICATION_KEY.FINGERPRINT_WORKING_INDICATED]: { employeeId: string; date: string };
	[NOTIFICATION_KEY.FINGERPRINT_LEAVE_CONFIRMED]: { employeeId: string; date: string };

	[NOTIFICATION_KEY.ROLE_PERMISSION_UPDATED]: {
		historyId: string;
		roleId: string;
		roleName: string;
	};
	[NOTIFICATION_KEY.USER_PERMISSION_UPDATED]: {
		historyId: string;
		userId: string;
		userName: string;
	};

	[NOTIFICATION_KEY.USER_ROLE_UPDATED]: { roleId: string };
	[NOTIFICATION_KEY.MISSING_ITEM_REQUEST_REJECTED]: {
		missingItemRequestId: string;
	};
	[NOTIFICATION_KEY.MISSING_ITEM_CONVERTED_TO_MATERIAL_REQUEST]: {
		missingItemRequestId: string;
		materialRequestId: string;
	};
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_REPORTED]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_PERSON_STRUCK]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_INFO_REQUESTED]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_INFO_RECEIVED]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_MARKED_FOR_PRESIDENT_REVIEW]: {
		vehicleAccidentReportId: string;
		reportId: number;
	};
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_PENDING_PRESIDENT_REVIEW]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_INTERNALLY_RESOLVED]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_READY_FOR_INSURANCE]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_INSURANCE_SUBMITTED]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.DRUG_SCREEN_REQUIRED_COORDINATOR]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.DRUG_SCREEN_REQUIRED_TECHNICIAN]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.DRUG_SCREEN_REQUIRED_ADMIN]: { vehicleAccidentReportId: string; reportId: number };
	[NOTIFICATION_KEY.VEHICLE_BREAKDOWN_REPORTED]: { vehicleBreakdownReportId: string; reportId: number };
	[NOTIFICATION_KEY.DRIVING_SAFETY_VIOLATION_REPORTED]: { drivingSafetyViolationReportId: string; reportId: number };
	[NOTIFICATION_KEY.JOB_SITE_INJURY_REPORTED]: {
		jobSiteInjuryReportId?: string;
		jobSiteSafetyViolationId?: string;
		reportId: number;
	};
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_REPORT_CREATED_BY_ADMIN]: {
		jobSiteInjuryReportId?: string;
		jobSiteSafetyViolationId?: string;
		reportId: number;
	};
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_VIOLATION_REPORTED]: {
		jobSiteInjuryReportId?: string;
		jobSiteSafetyViolationId?: string;
		reportId: number;
	};
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_MARKED_FOR_PRESIDENT_REVIEW]: {
		jobSiteInjuryReportId?: string;
		jobSiteSafetyViolationId?: string;
		reportId: number;
	};
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_PENDING_PRESIDENT_REVIEW]: {
		jobSiteInjuryReportId?: string;
		jobSiteSafetyViolationId?: string;
		reportId: number;
	};
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_INTERNALLY_RESOLVED]: {
		jobSiteInjuryReportId?: string;
		jobSiteSafetyViolationId?: string;
		reportId: number;
	};
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_RESOLVED]: {
		jobSiteInjuryReportId?: string;
		jobSiteSafetyViolationId?: string;
		reportId: number;
	};
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_CLOSED_FOR_TECHNICIAN]: {
		jobSiteInjuryReportId?: string;
		jobSiteSafetyViolationId?: string;
		reportId: number;
	};
};

export const NotificationTitleMap: Record<NOTIFICATION_KEY, string> = {
	[NOTIFICATION_KEY.DAY_LOG_TIME_MISMATCH]: "Day Log Time Mismatch",
	[NOTIFICATION_KEY.EARLY_DAY_START]: "Early Day Start",
	[NOTIFICATION_KEY.FOREMAN_ADDED_STOP]: "Foreman Added Stop",
	[NOTIFICATION_KEY.ADMIN_JOB_ALERT]: "Admin Job Alert",
	[NOTIFICATION_KEY.ADMIN_ALERT]: "Admin Alert",
	[NOTIFICATION_KEY.JOB_NOT_COMPLETED]: "Job Not Completed",
	[NOTIFICATION_KEY.ETR]: "Extended Time Request",
	[NOTIFICATION_KEY.JOB_TIME_OVERRIDE]: "Job Time Override",
	[NOTIFICATION_KEY.EMPLOYEE_RESCHEDULED_JOB]: "Employee Rescheduled Job",
	[NOTIFICATION_KEY.JOB_SCHEDULE_DATE_CHANGED]: "Job Schedule Date Changed",
	[NOTIFICATION_KEY.EMPLOYEE_LATE_REASON]: "Employee Late Reason",
	[NOTIFICATION_KEY.LATENESS_ALERT]: "Lateness Alert",
	[NOTIFICATION_KEY.EMPLOYEE_ADDED_NOTE]: "Employee Added Note",
	[NOTIFICATION_KEY.ATTENDANCE_APPROVAL]: "Attendance",
	[NOTIFICATION_KEY.TECHNICAL_ISSUE]: "Technical Issue",
	[NOTIFICATION_KEY.MIDDAY_STOP]: "New Job Request",
	[NOTIFICATION_KEY.GPS_TIME_MISMATCH]: "GPS Time Mismatch",
	[NOTIFICATION_KEY.TECHNICAL_ISSUE_UPDATE]: "Technical Issue Update",
	[NOTIFICATION_KEY.TRAVEL_PAY_REQUEST]: "Travel Pay Request",
	[NOTIFICATION_KEY.LATE_DAY_START]: "Late Day Start",
	[NOTIFICATION_KEY.TRAVEL_PAY_REQUEST_NOTE_ADDED]: "Travel Pay Request Note Added",
	[NOTIFICATION_KEY.TRAVEL_PAY_REQUEST_CREATED]: "Travel Pay Request Created",
	[NOTIFICATION_KEY.SYSTEM_TRAVEL_PAY_REQUEST_STATUS_UPDATE]: "System Travel Pay Request Status Update",
	[NOTIFICATION_KEY.ADMIN_JOB_DELETED]: "Admin Job Deleted",
	[NOTIFICATION_KEY.VEHICLE_SWAP]: "Vehicle Swap",
	[NOTIFICATION_KEY.JOB_MARK_AS_NOT_READY_BY_EMPLOYEE]: "Job Mark As Not Ready By Employee",
	[NOTIFICATION_KEY.JOB_MARK_AS_NOT_READY]: "Job Mark As Not Ready",
	[NOTIFICATION_KEY.JOB_UPDATE_REMINDER]: "Job Update Reminder",
	[NOTIFICATION_KEY.OVERTIME_REQUEST]: "Overtime Request",
	[NOTIFICATION_KEY.EMPLOYEE_ALERT]: "Employee Alert",
	[NOTIFICATION_KEY.JOB_DATE_UPDATE]: "Job Date Update",
	[NOTIFICATION_KEY.SCHEDULE_PUBLISHED]: "Schedule Published",
	[NOTIFICATION_KEY.LOG_TIME_REMINDER]: "Log Time Reminder",
	[NOTIFICATION_KEY.EMPLOYEE_REMOVED_FROM_DAILY_JOB]: "Employee Removed From Daily Job",
	[NOTIFICATION_KEY.JOB_MARK_AS_READY]: "Job Mark As Ready",
	[NOTIFICATION_KEY.ADMIN_ALLOW_WEEKEND_SELF_SCHEDULING]: "Admin Allowed Weekend Self Scheduling",
	[NOTIFICATION_KEY.ADMIN_DISALLOW_WEEKEND_SELF_SCHEDULING]: "Admin Disallowed Weekend Self Scheduling",
	[NOTIFICATION_KEY.EMPLOYEE_WEEKEND_SELF_SCHEDULED_JOB]: "Employee Weekend Self Scheduled Job",
	[NOTIFICATION_KEY.EMPLOYEE_SELF_SCHEDULED_JOB]: "Employee Weekday Self Scheduled Job",
	[NOTIFICATION_KEY.EMPLOYEE_GPS_OFFLINE]: "GPS Alert!",
	[NOTIFICATION_KEY.RELEASE_NOTE]: "Release Note",
	[NOTIFICATION_KEY.APP_UPDATES]: "App Updates",
	[NOTIFICATION_KEY.JOB_PUBLISH]: "Job Publish",
	[NOTIFICATION_KEY.GEOTAB_REGAINED_POWER]: "Geotab Regain Power",
	[NOTIFICATION_KEY.ADMIN_UPDATE_WEEKEND_WORKING_MODE]: "Weekend Working",
	[NOTIFICATION_KEY.WEEKEND_VOLUNTARY_REQUEST_SENT]: "Weekend Voluntary Request",
	[NOTIFICATION_KEY.WEEKEND_VOLUNTARY_RESPONSE_SUBMITTED]: "Weekend Voluntary Response",
	[NOTIFICATION_KEY.WEEKEND_VOLUNTARY_EMPLOYEE_RESPONSE_REVIEWED]: "Weekend Voluntary Response Reviewed",
	[NOTIFICATION_KEY.WEEKEND_SLOT_AVAILABLE]: "Weekend Slot Available",
	[NOTIFICATION_KEY.CREW_ASSIGNED_TO_JOB]: "Job Assigned To Crew",
	[NOTIFICATION_KEY.SUBCONTRACTOR_JOB_CREATED_AND_CREW_ASSIGNMENT]: "Subcontractor Job Created",
	[NOTIFICATION_KEY.WORK_ORDER_SCHEDULED]: "Work Order Scheduled",
	[NOTIFICATION_KEY.USER_WEEKEND_WORK_DELETED]: "Weekend Work Deleted",
	[NOTIFICATION_KEY.JOB_MARKED_AS_DNW]: "Job Marked As Did Not Work",
	[NOTIFICATION_KEY.ADMIN_ALLOW_SELF_SCHEDULING]: "Admin Allowed Self Scheduling",
	[NOTIFICATION_KEY.ADMIN_DISALLOW_SELF_SCHEDULING]: "Admin Disallowed Self Scheduling",
	[NOTIFICATION_KEY.JOB_MARK_AS_NOT_READY_BY_SUB_CREW]: "Job Mark As Not Ready By Crew",
	[NOTIFICATION_KEY.JOB_NOT_COMPLETED_BY_SUB_CREW]: "Job Not Completed By Crew",
	[NOTIFICATION_KEY.LATE_START_AND_EARLY_QUIT]: "Late Start & Early Quit",
	[NOTIFICATION_KEY.GPS_IDLE_TIME]: "GPS Idle Time",
	[NOTIFICATION_KEY.GPS_AFTER_HOUR_USAGE]: "GPS After Hour Usage",
	[NOTIFICATION_KEY.GPS_AFTER_HOUR_USAGE_NOTE]: "GPS After Hour Usage Note",
	[NOTIFICATION_KEY.MATERIAL_REQUEST]: "Material Request",
	[NOTIFICATION_KEY.MISSING_ITEM_REQUEST]: "Unknown Item Request",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_ASSIGNED]: "Material Request Assigned",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_APPROVED]: "Material Request Approved",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_REJECTED]: "Material Request Rejected",
	[NOTIFICATION_KEY.MISSING_ITEM_REQUEST_NOTE]: "Unknown Item Request Note",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_NOTE]: "Material Request Note",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_APPROVED_CREW]: "Material Request Approved",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_REJECTED_CREW]: "Material Request Rejected",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_REASSIGNED]: "Material Request Reassigned",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_REASSIGNED_CREW]: "Material Request Reassigned",
	[NOTIFICATION_KEY.MATERIAL_REQUEST_CROSS_ASSIGNED]: "Material Request Reassigned",
	[NOTIFICATION_KEY.FINGERPRINT_WORKING_INDICATED]: "Attendance Approval",
	[NOTIFICATION_KEY.FINGERPRINT_LEAVE_CONFIRMED]: "Attendance Approval",
	[NOTIFICATION_KEY.ROLE_PERMISSION_UPDATED]: "Roles and Permissions Updated",
	[NOTIFICATION_KEY.USER_PERMISSION_UPDATED]: "Roles and Permissions Updated",
	[NOTIFICATION_KEY.USER_ROLE_UPDATED]: "Roles and Permissions Updated",
	[NOTIFICATION_KEY.JOB_COMPLETED]: "Job Completed",
	[NOTIFICATION_KEY.MISSING_ITEM_REQUEST_REJECTED]: "Material Unknown Item Request Rejected",
	[NOTIFICATION_KEY.MISSING_ITEM_CONVERTED_TO_MATERIAL_REQUEST]:
		"Material Unknown Item Request Converted To Material Request",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_REPORTED]: "New Vehicle Accident Reported",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_PERSON_STRUCK]: "Person Struck in Vehicle Accident",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_INFO_REQUESTED]: "Additional Information Requested",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_INFO_RECEIVED]: "Additional Information Received",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_MARKED_FOR_PRESIDENT_REVIEW]: "Accident Marked for President's Review",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_PENDING_PRESIDENT_REVIEW]: "Vehicle Accident Pending Your Review",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_INTERNALLY_RESOLVED]: "Accident Internally Resolved",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_READY_FOR_INSURANCE]: "Accident Ready for Insurance Submission",
	[NOTIFICATION_KEY.VEHICLE_ACCIDENT_INSURANCE_SUBMITTED]: "Insurance Claim Submitted",
	[NOTIFICATION_KEY.DRUG_SCREEN_REQUIRED_COORDINATOR]: "Drug Screen Required",
	[NOTIFICATION_KEY.DRUG_SCREEN_REQUIRED_TECHNICIAN]: "Drug Screen Required",
	[NOTIFICATION_KEY.DRUG_SCREEN_REQUIRED_ADMIN]: "Drug Screen Required",
	[NOTIFICATION_KEY.VEHICLE_BREAKDOWN_REPORTED]: "Vehicle Breakdown Reported",
	[NOTIFICATION_KEY.DRIVING_SAFETY_VIOLATION_REPORTED]: "Safety Violation Reported",
	[NOTIFICATION_KEY.JOB_SITE_INJURY_REPORTED]: "New Job Site Safety Issue Reported",
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_REPORT_CREATED_BY_ADMIN]: "Job Site Safety Report Created",
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_VIOLATION_REPORTED]: "Job Site Safety Violation Reported",
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_MARKED_FOR_PRESIDENT_REVIEW]: "Incident Marked for President's Review",
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_PENDING_PRESIDENT_REVIEW]: "Job Site Safety Incident Pending Your Review",
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_INTERNALLY_RESOLVED]: "Incident Internally Resolved",
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_RESOLVED]: "Incident Resolved",
	[NOTIFICATION_KEY.JOB_SITE_SAFETY_CLOSED_FOR_TECHNICIAN]: "Job Site Safety Incident Closed",
};

export type NotificationUnion = {
	[K in NOTIFICATION_KEY]: { mappedTitle: K; parsedData: INotificationDataMap[K] };
}[NOTIFICATION_KEY];
