import { INCIDENT_REPORT_STATUS } from "@/module/driving-safety/incident-reports/utils/enums";

import { TECHNICIAN_REPORT_STATUS } from "../enums";

const ACCIDENT_STATUS_TO_TECHNICIAN: Record<INCIDENT_REPORT_STATUS, TECHNICIAN_REPORT_STATUS> = {
	[INCIDENT_REPORT_STATUS.DRAFT]: TECHNICIAN_REPORT_STATUS.DRAFT,
	[INCIDENT_REPORT_STATUS.PENDING]: TECHNICIAN_REPORT_STATUS.PENDING,
	[INCIDENT_REPORT_STATUS.PENDING_SECOND_REVIEW]: TECHNICIAN_REPORT_STATUS.PENDING,
	[INCIDENT_REPORT_STATUS.PENDING_THIRD_REVIEW]: TECHNICIAN_REPORT_STATUS.PENDING,
	[INCIDENT_REPORT_STATUS.COORDINATE]: TECHNICIAN_REPORT_STATUS.PENDING,
	[INCIDENT_REPORT_STATUS.WITH_INSURANCE]: TECHNICIAN_REPORT_STATUS.PENDING,
	[INCIDENT_REPORT_STATUS.RESOLVED]: TECHNICIAN_REPORT_STATUS.APPROVED,
	[INCIDENT_REPORT_STATUS.REJECTED]: TECHNICIAN_REPORT_STATUS.REJECTED,
	[INCIDENT_REPORT_STATUS.ADDITIONAL_INFO_REQUESTED]: TECHNICIAN_REPORT_STATUS.ADDITIONAL_INFO_REQUESTED,
};

export const toTechnicianStatus = (status?: INCIDENT_REPORT_STATUS): TECHNICIAN_REPORT_STATUS | undefined =>
	status && ACCIDENT_STATUS_TO_TECHNICIAN[status];

export const TECHNICIAN_STATUS_LABEL: Record<TECHNICIAN_REPORT_STATUS, string> = {
	[TECHNICIAN_REPORT_STATUS.DRAFT]: "Draft",
	[TECHNICIAN_REPORT_STATUS.PENDING]: "Pending",
	[TECHNICIAN_REPORT_STATUS.APPROVED]: "Approved",
	[TECHNICIAN_REPORT_STATUS.REJECTED]: "Rejected",
	[TECHNICIAN_REPORT_STATUS.ADDITIONAL_INFO_REQUESTED]: "Additional Info Requested",
};
