import type { AdminMissingItemRequest } from "../../missing-item-requests-admin/utils/types";
import { MATERIAL_REQUEST_TYPE } from "./enums";
import type { MaterialRequestRow } from "./types";

export const mapMissingItemToRow = (item: AdminMissingItemRequest): MaterialRequestRow => ({
	id: `missing-${item.id}`,
	materialRequestId: item.id,
	missingItemOriginalId: item.id,
	missingItemForemanId: item.foreman?.id ?? null,
	typeOfRequest: MATERIAL_REQUEST_TYPE.MISSING_ITEM,
	requestId: item.requestId,
	requestDate: item.date ?? item.createdAt,
	jobId: null,
	jobName: item.jobName ?? null,
	phaseName: null,
	phaseNumber: null,
	phase: item.phase ?? null,
	requestedBy: item.user?.name ?? null,
	requestedByDepartment: null,
	builderName: null,
	projectName: null,
	foremanNote: item.foremanNote ?? null,
	reason: item.description ?? "",
	// MaterialRequest required fields
	jobDailyRecordId: item.jobDailyRecordId ?? "",
	date: item.date ?? item.createdAt,
	isDeliveryOnBCEWTruck: null,
	assignTo: null,
	assignToId: null,
	isApproved: null,
	isRejected: null,
	model: "",
	userId: item.user?.id ?? "",
	createdAt: item.createdAt,
	updatedAt: item.updatedAt,
	jobDailyRecord: null,
	// PullListItem required fields
	partId: "",
	name: "",
	code: "",
	vendor: "",
	stockStatus: "",
	orders: "",
	received: "",
	backorder: "",
	quantity: item.quantity != null ? String(item.quantity) : "",
	referenceId: null,
	workOrderNumber: null,
	pullListConfirmed: null,
	additionalQuantity: null,
	receivedInput: null,
	needed: null,
	note: null,
	approveNote: null,
	rejectNote: null,
	warehouseManagerNote: null,
	officeNote: null,
	procurementSpecialistNote: null,
	images: item.images.map((img) => ({ id: img.keyFile || img.url, url: img.url, keyFile: img.keyFile })),
	assigneeIds: [],
	assigneeNamesByRole: {},
	prospectiveAssigneeNamesByRole: {},
});
